"""initial_schema

Revision ID: 256a2db15dc2
Revises: 
Create Date: 2026-04-23 06:54:21.473442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '256a2db15dc2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('imap_host', sa.String(length=255), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_poll_error', sa.Text(), nullable=True),
    sa.Column('last_uid', sa.BigInteger(), nullable=False),
    sa.Column('folder_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_accounts_email', 'accounts', ['email'], unique=False)
    op.create_index('idx_accounts_is_active', 'accounts', ['is_active'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('llm_base_url', sa.String(length=255), nullable=True),
    sa.Column('llm_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('llm_temperature', sa.Float(), nullable=False),
    sa.Column('polling_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('auto_mode', sa.Boolean(), nullable=False),
    sa.Column('max_few_shot_examples', sa.Integer(), nullable=False),
    sa.Column('body_excerpt_length', sa.Integer(), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('email_retention_days', sa.Integer(), nullable=False),
    sa.Column('phishing_auto_quarantine', sa.Boolean(), nullable=False),
    sa.Column('initial_fetch_since', sa.Date(), nullable=True),
    sa.Column('app_password', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_settings',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('default_category_action', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('email_threads',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('subject_normalized', sa.String(length=512), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_count', sa.Integer(), nullable=False),
    sa.Column('last_email_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('awaiting_reply', sa.Boolean(), nullable=False),
    sa.Column('awaiting_response', sa.Boolean(), nullable=False),
    sa.Column('reply_needed_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_threads_account_id', 'email_threads', ['account_id'], unique=False)
    op.create_index('idx_threads_awaiting', 'email_threads', ['awaiting_reply', 'awaiting_response'], unique=False, postgresql_where='awaiting_reply = TRUE OR awaiting_response = TRUE')
    op.create_table('rules',
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('natural_text', sa.Text(), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_count', sa.Integer(), nullable=False),
    sa.Column('last_matched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rules_account_active', 'rules', ['account_id', 'is_active'], unique=False)
    op.create_index('idx_rules_priority', 'rules', ['priority'], unique=False)
    op.create_table('sender_profiles',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('email_address', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('primary_category', sa.String(length=50), nullable=True),
    sa.Column('total_emails', sa.Integer(), nullable=False),
    sa.Column('last_email_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_newsletter', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sender_profiles_address', 'sender_profiles', ['account_id', 'email_address'], unique=True)
    op.create_index('idx_sender_profiles_blocked', 'sender_profiles', ['is_blocked'], unique=False, postgresql_where='is_blocked = TRUE')
    op.create_index('idx_sender_profiles_domain', 'sender_profiles', ['domain'], unique=False)
    op.create_table('emails',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('in_reply_to', sa.String(length=512), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('reply_to', sa.String(length=255), nullable=True),
    sa.Column('to_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cc_addresses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body_excerpt', sa.Text(), nullable=True),
    sa.Column('body_html_excerpt', sa.Text(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=False),
    sa.Column('attachment_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('folder', sa.String(length=255), nullable=True),
    sa.Column('original_folder', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['email_threads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emails_account_date', 'emails', ['account_id', 'date'], unique=False)
    op.create_index('idx_emails_account_uid', 'emails', ['account_id', 'uid'], unique=True)
    op.create_index('idx_emails_date', 'emails', ['date'], unique=False)
    op.create_index('idx_emails_folder', 'emails', ['folder'], unique=False)
    op.create_index('idx_emails_from_address', 'emails', ['from_address'], unique=False)
    op.create_index('idx_emails_message_id', 'emails', ['message_id'], unique=False)
    op.create_index('idx_emails_not_archived', 'emails', ['is_archived'], unique=False, postgresql_where='is_archived = FALSE')
    op.create_index('idx_emails_processing_status', 'emails', ['processing_status'], unique=False)
    op.create_index('idx_emails_thread_id', 'emails', ['thread_id'], unique=False)
    op.create_table('newsletters',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('sender_profile_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sender_address', sa.String(length=255), nullable=False),
    sa.Column('unsubscribe_link', sa.Text(), nullable=True),
    sa.Column('unsubscribe_mailto', sa.String(length=255), nullable=True),
    sa.Column('unsubscribe_method', sa.String(length=20), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('total_received', sa.Integer(), nullable=False),
    sa.Column('total_read', sa.Integer(), nullable=False),
    sa.Column('frequency_days', sa.Float(), nullable=True),
    sa.Column('last_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_profile_id'], ['sender_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_newsletters_account_sender', 'newsletters', ['account_id', 'sender_address'], unique=True)
    op.create_index('idx_newsletters_status', 'newsletters', ['subscription_status'], unique=False)
    op.create_table('sender_category_stats',
    sa.Column('sender_profile_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('corrected_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['sender_profile_id'], ['sender_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sender_cat_stats_profile_cat', 'sender_category_stats', ['sender_profile_id', 'category'], unique=True)
    op.create_table('actions',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_reversible', sa.Boolean(), nullable=False),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_actions_account_date', 'actions', ['account_id', 'created_at'], unique=False)
    op.create_index('idx_actions_created_at', 'actions', ['created_at'], unique=False)
    op.create_index('idx_actions_email_id', 'actions', ['email_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_account_date', 'activity_logs', ['account_id', 'created_at'], unique=False)
    op.create_index('idx_activity_created_at', 'activity_logs', ['created_at'], unique=False)
    op.create_index('idx_activity_event_type', 'activity_logs', ['event_type'], unique=False)
    op.create_table('classifications',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('is_phishing', sa.Boolean(), nullable=False),
    sa.Column('phishing_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('classified_by', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_id')
    )
    op.create_index('idx_classifications_category', 'classifications', ['category'], unique=False)
    op.create_index('idx_classifications_is_phishing', 'classifications', ['is_phishing'], unique=False, postgresql_where='is_phishing = TRUE')
    op.create_index('idx_classifications_review', 'classifications', ['status'], unique=False, postgresql_where="status = 'review'")
    op.create_index('idx_classifications_status', 'classifications', ['status'], unique=False)
    op.create_table('email_urls',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('suspicion_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_urls_email_id', 'email_urls', ['email_id'], unique=False)
    op.create_index('idx_email_urls_suspicious', 'email_urls', ['is_suspicious'], unique=False, postgresql_where='is_suspicious = TRUE')
    op.create_table('corrections',
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('classification_id', sa.UUID(), nullable=False),
    sa.Column('original_category', sa.String(length=50), nullable=False),
    sa.Column('corrected_category', sa.String(length=50), nullable=False),
    sa.Column('original_confidence', sa.Float(), nullable=True),
    sa.Column('user_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_corrections_categories', 'corrections', ['original_category', 'corrected_category'], unique=False)
    op.create_index('idx_corrections_created_at', 'corrections', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_corrections_created_at', table_name='corrections')
    op.drop_index('idx_corrections_categories', table_name='corrections')
    op.drop_table('corrections')
    op.drop_index('idx_email_urls_suspicious', table_name='email_urls', postgresql_where='is_suspicious = TRUE')
    op.drop_index('idx_email_urls_email_id', table_name='email_urls')
    op.drop_table('email_urls')
    op.drop_index('idx_classifications_status', table_name='classifications')
    op.drop_index('idx_classifications_review', table_name='classifications', postgresql_where="status = 'review'")
    op.drop_index('idx_classifications_is_phishing', table_name='classifications', postgresql_where='is_phishing = TRUE')
    op.drop_index('idx_classifications_category', table_name='classifications')
    op.drop_table('classifications')
    op.drop_index('idx_activity_event_type', table_name='activity_logs')
    op.drop_index('idx_activity_created_at', table_name='activity_logs')
    op.drop_index('idx_activity_account_date', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('idx_actions_email_id', table_name='actions')
    op.drop_index('idx_actions_created_at', table_name='actions')
    op.drop_index('idx_actions_account_date', table_name='actions')
    op.drop_table('actions')
    op.drop_index('idx_sender_cat_stats_profile_cat', table_name='sender_category_stats')
    op.drop_table('sender_category_stats')
    op.drop_index('idx_newsletters_status', table_name='newsletters')
    op.drop_index('idx_newsletters_account_sender', table_name='newsletters')
    op.drop_table('newsletters')
    op.drop_index('idx_emails_thread_id', table_name='emails')
    op.drop_index('idx_emails_processing_status', table_name='emails')
    op.drop_index('idx_emails_not_archived', table_name='emails', postgresql_where='is_archived = FALSE')
    op.drop_index('idx_emails_message_id', table_name='emails')
    op.drop_index('idx_emails_from_address', table_name='emails')
    op.drop_index('idx_emails_folder', table_name='emails')
    op.drop_index('idx_emails_date', table_name='emails')
    op.drop_index('idx_emails_account_uid', table_name='emails')
    op.drop_index('idx_emails_account_date', table_name='emails')
    op.drop_table('emails')
    op.drop_index('idx_sender_profiles_domain', table_name='sender_profiles')
    op.drop_index('idx_sender_profiles_blocked', table_name='sender_profiles', postgresql_where='is_blocked = TRUE')
    op.drop_index('idx_sender_profiles_address', table_name='sender_profiles')
    op.drop_table('sender_profiles')
    op.drop_index('idx_rules_priority', table_name='rules')
    op.drop_index('idx_rules_account_active', table_name='rules')
    op.drop_table('rules')
    op.drop_index('idx_threads_awaiting', table_name='email_threads', postgresql_where='awaiting_reply = TRUE OR awaiting_response = TRUE')
    op.drop_index('idx_threads_account_id', table_name='email_threads')
    op.drop_table('email_threads')
    op.drop_table('account_settings')
    op.drop_table('settings')
    op.drop_index('idx_accounts_is_active', table_name='accounts')
    op.drop_index('idx_accounts_email', table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
